# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            PYTHON
tagline:          'Community'
description:      'Moldova Community'
baseurl:          /


paginate:         5

# deployment
host: 0.0.0.0
port: 4000

plugins:
  - jekyll-paginate