# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        /:categories/:title

# Setup
title:            PYTHON
tagline:          'Community'
description:      'Community website of Python Developers from Moldova'
baseurl:          /


paginate:         5

# deployment
host: 0.0.0.0
port: 4000

plugins:
  - jekyll-paginate