# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        none

# Setup
title:            'Python Moldova Community'
tagline:          'Developers, Events and News'
description:      'Community website of Python Developers from Moldova'
baseurl:          /

# deployment
host: 0.0.0.0
port: 4000

plugins:
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 5

collections:
  jobs:
    output: true
    permalink: /jobs/:path/
